### ISSUE TITLE
1.1 Not Work.

### ISSUE THREAD

**Issue by BexiPE** [NewTesseractTeam/NewTesseract#5] opened 2017-06-06 16:49 UTC
Joining whit 1.1 not work...

**Comment by FunnyBuddys** [comment] 2017-06-06 19:43
We work on it ;)

**Comment by FunnyBuddys** [comment] 2017-06-06 19:44
Duplicate of https://github.com/NewTesseractTeam/NewTesseract/issues/3

**Closed** 2017-06-06 19:44 UTC
Labels: duplicate

**Comment by opkiler22789** [comment] 2017-06-08 08:00
#3
